#include "sensor.hpp"
#include "log.h"

RTIMU * sensorInit(){
    //  Using RTIMULib here allows it to use the .ini file generated by RTIMULibDemo.
    //  Or, you can create the .ini in some other directory by using:
    //      RTIMUSettings *settings = new RTIMUSettings("<directory path>", "RTIMULib");
    //  where <directory path> is the path to where the .ini file is to be loaded/saved
    RTIMUSettings *settings = new RTIMUSettings("RTIMULib");
    if(settings==NULL){
        logString("NEW FAIL : RTIMUSettings ->settings");
        return NULL;
    }

    RTIMU *imu = RTIMU::createIMU(settings);

    if ( imu->IMUType() == RTIMU_TYPE_NULL) {
    	logString("No IMU found");
        return NULL;
    }

    //  This is an opportunity to manually override any settings before the call IMUInit
    //  set up IMU
    imu->IMUInit();

    //  this is a convenient place to change fusion parameters
    imu->setSlerpPower(0.02);
    imu->setGyroEnable(true);
    imu->setAccelEnable(true);
    imu->setCompassEnable(true);
    return imu;
}
